theme: jekyll-theme-cayman
title: "Matthew Whalen <br/> PhD Student Univeristy of Michigan"
subtitle: "PhD Student Univeristy of Michigan"
exclude:
  "README.md"

include: [_pages]
url: https://mwhalen18.github.io

